package com.syc.cloud.core.exception;

/**
 * @author 33992
 * @since 2021/10/15
 **/
public class AuthException extends RuntimeException {
}
